### PR TITLE
New custom deduplication method based on UMI-tools API

### PR DESCRIPTION
**Pull request by cnluzon**
This is a WIP to replace the current deduplication method. It is still not included in the workflow, only the python code for new deduplication is included. Even if it's a WIP, it is already open for discussion and comments :)

# Current deduplication
1. Use `se_bam` to make a pass at the original BAM file and keep only R1 reads.
2. Deduplicate this single-end BAM with je-markdupes.
3. Use the IDs marked as duplicates in (2) to mark duplicate "pairs" in (1).

## Issues
1. Aligned reads where R1 is missing are not considered in the deduplication process.
2. Multimappers (low mapping quality reads) are deduplicated considering the mapping position accurate.
3. Library size estimation is lost, because JE does not estimate on single fragments.
4. Workflow is complicated.

# Suggested deduplication
What is proposed here is to use umitools `UMIClusterer` in custom python code so we can deduplicate in a single step.

The workflow follows this idea:
1. Make a **position-based index** of the BAM file with only the information relevant for this for R1 reads and R2-only reads - i.e. reads that don't have a mapped R1 present in the alignment (NOTE: I have checked if `pysam` would give me an index exactly how I needed it and did not find a good answer. I prototyped a bit accessing the reads directly through the BAM iterator but that was way slower than this solution. But I am pretty sure this can be improved). 
2. Gather all the **multimapping reads** (under a certain mapping quality threshold) to be deduplicated based only on sequence. The rationale for this is that multi mapping reads could have been assigned to other places, hence deduplicating by position can overlook duplicates. Deduplicating by sequence has other shortcomings (it is more costful and could be inaccurate based only on sequence). However we think sequence + UMI can be a good amount of information to get the real duplicates.
3. **Deduplicate reads in (1) by position**, using UMIClusterer to find the best candidate across similar UMIs from reads that map to the same position. The rest of the reads are considered duplicates. When there is more than one read with the same UMI, the best score is used, in the same way as je was doing: sum of base scores. This way we can better compare results, since the major selection criteria is matched.
4. **Deduplicate multimappers** using UMI and sequence: This is done hierarchically. First grouping by UMI, then by a sequence stub of a certain length that is kept for the reads identified as multimappers.
5. Write a BAM file excluding all reads mapped as duplicates (and all unmapped as well).

Step (4) so far seems to work very well, even though it's counter intuitive (one would want to cluster first by sequence, then by UMI). But UMIClusterer is very sensitive to sequence size (this problem has very high complexity on sequence length), and very efficient for sequences of 6nt (our UMI size), also doable I think for 8nt sequences, which we sometimes have. In the event that we want to keep same behavior as before, and treat multi mappers as anything else, we can set the mapping quality threshold to 0. 

I have tested deduplicating BAM files based solely on this and comparing to deduplicating by Picard and results are similar enough to consider this a good option, considering that multimappers are not very well deduplicated anyway. 

I added a little stub test file, but I am aware that it tests very little so far. I am not an expert on python testing, but I will improve this as soon as I can.

### CODE REVIEW

**Comment by cnluzon** [comment]
Note that this is quite a memory demanding method. 

We have had memory issues in the past with the other mark_duplicates tools (je and/or picard), but in this case the pass/indexing at the BAM file is less optimized. The question is whether we always have alignments that are not too large. When I tested for alignments in our datasets, I got BAM files around 1GB and it worked nicely even on my local computer. Right now I found a case where we have larger alignments so I am doing a stress test to see how much we can get out of this approach.

The memory stress can be relieved by deduplicating in chunks. Processing time can be also improved by parallelizing this step.

In the case of the multimappers we would still need to do it all together, since we are not using position, but the second step clustering could also be parallelized.

**Comment by cnluzon** [comment]
I have found another problem with the UMI-tools deduplication using `UMIclusterer`. I cannot get the same number of duplicates twice, I am assuming there is some random seeding at some point that overwrites mine, because even if I fix a seed I still get the deduplication with a slightly different value each time.

I am going to close this PR as I do not have intention to merge as it is. I will look at a better solution to this and retry in the future.

**Comment by marcelm** [comment]
Hi, I was working on some other things when you opened this PR. Now that you’ve closed, can I just ignore it for now?

**Comment by cnluzon** [comment]
Yes, feel free to ignore it :) I thought the idea was more mature than it was. I will come back with a cleaner take on it in the next weeks! Thanks!

**Pull request closed without merging**
